// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 17/6/2025, 4:24:17 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/DELL/konaseema_ghumaghumalu/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DELL/konaseema_ghumaghumalu/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DELL/konaseema_ghumaghumalu/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DELL/konaseema_ghumaghumalu/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DELL/konaseema_ghumaghumalu/plugins/**/*.{js,ts,mjs}","C:/Users/DELL/konaseema_ghumaghumalu/composables/**/*.{js,ts,mjs}","C:/Users/DELL/konaseema_ghumaghumalu/utils/**/*.{js,ts,mjs}","C:/Users/DELL/konaseema_ghumaghumalu/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DELL/konaseema_ghumaghumalu/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DELL/konaseema_ghumaghumalu/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DELL/konaseema_ghumaghumalu/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;